### PR TITLE
Parse graph to extract protein seq

### PR DESCRIPTION
**Pull request by pierrepo**
This PR uses:
- `graph.nodes.items()` to parse all node attributes at once.
- the dictionnary provided by MDAanalysis for the 3-letter code -> 1-letter code residue conversion.

### CODE REVIEW

**Comment by KarinDuong** [comment]
@pierrepo I can't merge, there is a conflict

**Comment by pierrepo** [comment]
@KarinDuong it should be ok now

**Comment by pierrepo** [comment]
Oups, wait.

**Comment by pierrepo** [comment]
@KarinDuong it looks good

**Pull request merged**
